version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - run:
          name: run tests
          command: |
            python setup.py test

  deploy:
    branches:
      only:
        - master
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository = https://test.pypi.org/legacy/" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            pip install wheel
            python setup.py bdist_wheel --universal

      - run:
          name: upload to pypi
          command: |
            pip install twine
            twine upload dist/*
